# basic options
title: New-awesome-blog
author: Smart girl
email: 'vindar12342019@gmail.com'
description: A wonderful blog
github_username: vindar42

# Build settings
markdown: kramdown
theme: minima
